name: 'transform'
version: '1.0.0'

profile: 'transform'

model-paths: ["transform/models"]
macro-paths: ["transform/macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  transform:
    staging:
      +schema: staging
      +materialized: table
    intermediate:
      +schema: intermediate
      +materialized: table
    core:
      +schema: core
      +materialized: table