transform:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      path: data/fpl_analytics.duckdb
      schema: staging
      threads: 2
    
    prod:
      type: duckdb
      path: "md:fpl_analytics?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      schema: staging
      threads: 2