# .dlt/secrets.toml
[destination.duckdb.credentials]
database = "data/fpl_analytics.duckdb"

[destination.motherduck]
database = "fpl_analytics"

[destination.motherduck.credentials]
motherduck_token = "env:MOTHERDUCK_TOKEN"   