name: Deploy FPL Analytics Backend to Modal

on:
  push:
    branches:
      - main
    paths:
      - 'modal/**'
      - 'extract_load/**'
      - 'transform/**'
      - 'pyproject.toml'
      - '.github/workflows/deploy-modal.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        
      - name: Set up Python
        run: uv python install
        
      - name: Install dependencies
        run: uv sync
        
      - name: Deploy to Modal
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
        run: |
          uv run modal deploy modal/fpl_analytics_backend.py